### ISSUE TITLE
Сохранение миниатюр на Amazon S3

### ISSUE THREAD

**Issue by php5developer** [MihailDev/yii2-elfinder#103]
Добрый день. Настроил хранилище Amazon S3. Все прекрасно работает, однако картинки сохраняются на локальный сервер. Существует решение чтобы миниатюры загружались на Амазон диск? У меня настроена балансировка. Теряется всякий смысл любых хранилищ, если миниатюры хранятся локально.

**Comment by MihailDev** [comment]
миниатюры сохраняются автоматом во временное хранилище  это логика ельфаиндера при переносе или переезде они пересоздаются автоматом! когда я разбирался тоже думал что лучше всё хранить на том же хранилище но чёт у меня не пошло и получилось только локально сделать!

**Comment by php5developer** [comment]
Понятно. Я уже свой ельфайндер забацал за это время. Честно, даже не тестировал на сервере. Увидел что файлы локально созданы, дальше не стал копаться..
