### ISSUE TITLE
Автовыбор языка

### ISSUE THREAD

**Issue by Beaten-Sect0r** [MihailDev/yii2-elfinder#104]
https://github.com/Studio-42/elFinder/issues/2201

**Comment by MihailDev** [comment]
я не думаю что это хорошая идея так как в приложение выбран определённый язык и если всё правильно настроить то всё будет правильно работать( язык по умолчанию берётся из приложения)

**Comment by Beaten-Sect0r** [comment]
в приложение выбран русский, elfinder грузит английский

**Comment by MihailDev** [comment]
проверю

**Comment by MihailDev** [comment]
а в шаблоне не передаёте поле language ?

**Comment by Beaten-Sect0r** [comment]
в шаблоне нет, странно сейчас вроде всё заработало, хотя я ни чего не менял, вероятно проблема была у меня лично.
