### ISSUE TITLE
Invalid backend configuration. Readable volumes not available

### ISSUE THREAD

**Issue by mastershaig** [MihailDev/yii2-elfinder#105]
I want to add Amazon S3 filesystem to my Yii2 Elfinder plugin. So I installed these plugins to my app:
```
composer require league/flysystem 
composer require league/flysystem-aws-s3-v3 
composer require creocoder/yii2-flysystem 
composer require mihaildev/yii2-elfinder 
composer require mihaildev/yii2-elfinder-flysystem
```
Then I added this configuration:

```
'components' => [
   // ... 
    'fs' => [
        'class' => 'common\components\AwsS3Filesystem',
        'key' => '{MYAMAZONKEY}',
        'secret' => '{MYAMAZONSECRET}',
        'bucket' => '{MYBUCKET}',
        'region' => 'us-east-1',
    ],
        // ...
],
```
Then my elfinder configuration:
```
'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'access' => ['@'],
            'disabledCommands' => ['netmount'],
            'root' => [
                'class' => 'mihaildev\elfinder\flysystem\Volume',
                'component' => 'fs'
            ],
        ]
    ],
```
After all, when I open the elfinder window this error happens:

```
Invalid backend configuration.
Readable volumes not available.
{"error":["errConf","errNoVolumes"],"debug":["Driver \"elFinderVolumeFlysystem\" does not exist"]}

```
Actually I followed this [tutorial](http://www.2amigos.us/blog/how-to-connect-elfinder-with-amazon-s3-for-yii2), but it didn't help. I can't figure out what's problem. Any help appreciated.

**Comment by MihailDev** [comment]
hello
elFinderVolumeFlysystem is from https://github.com/barryvdh/elfinder-flysystem-driver please check
if you have this class and extension (is required for mihaildev/yii2-elfinder-flysystem ("barryvdh/elfinder-flysystem-driver": "^0.2.0"))
