### ISSUE TITLE
Загрузка файлов другого формата

### ISSUE THREAD

**Issue by Mandzuk** [MihailDev/yii2-elfinder#106]
Добрый день. Подскажите, пожалуйста, как можно реализовать загрузку других файлов, к примеру формата mp3 ? Вот мой конфиг
`'controllerMap' => [ 'elfinder' => [ 'class' => 'mihaildev\elfinder\Controller', 'access' => ['@'], 'disabledCommands' => ['netmount'], 'roots' => [ [ 'baseUrl'=>Yii::$app->params['frontend_url'], 'basePath'=>'@frontend/web', 'path' => 'files/global', 'name' => 'Global', ], ] ] ]`

**Comment by MihailDev** [comment]
на данный момент не загружаются??
если нет пришлите шаблон с подключением и возможные ошибки сервера!! так как всё должно работать!

**Comment by Mandzuk** [comment]
Прошу прощение за долгий ответ. Нашел решение. Файлы загружались, но не отображались. Оказалось, нужно было добавить параметр `'filter' => 'image',` либо `'filter' => ['audio'],` при вызове виджета
