### ISSUE TITLE
Совместимость с php 7.2

### ISSUE THREAD

**Issue by delightalmighty** [MihailDev/yii2-elfinder#109]
Добрый день!
В Php 7.2 слово Object стало зарезервированным, соответственно в Yii 2.0.13 базовый класс Object переименовали в BaseObject.
Однако, класс Base наследуется от старого Object и при попытке использование расширения получаем fatal error.
Ожидается ли обновление кода расширения для совместимости с Yii 2.0.13 и Php 7.2? 
Спасибо!

**Comment by MihailDev** [comment]
установите дев версию там не так давно было обновление для пхп 7
https://github.com/MihailDev/yii2-elfinder/pull/107

**Comment by delightalmighty** [comment]
спасибо большое!
