### ISSUE TITLE
Not work in Yii 2.0.14+ / php 7.2

### ISSUE THREAD

**Issue by TimurSeyidov** [MihailDev/yii2-elfinder#114]
Hi. Current version worked on Yii 2.0.13 (php 7.2), but not working in Yii 2.0.14
Problem with php 7.2 (replace Object to BaseObject)

**Comment by SeymurHashimov** [comment]
Chg #15633: Deprecated yii\base\BaseObject::className() in favor of native PHP syntax ::class, which does not trigger autoloading (brandonkelly)
https://github.com/yiisoft/yii2/blob/2.0.14/framework/CHANGELOG.md

**Comment by MihailDev** [comment]
please install dev version
https://github.com/MihailDev/yii2-elfinder/pull/107
