### ISSUE TITLE
Kartik Tree Manager + CKEditor + Elfinder

### ISSUE THREAD

**Issue by mtc-toolbox** [MihailDev/yii2-elfinder#133]
Доброго времени !

Advanced Template. Backend.

Делаю такую штуку:
backend\config\main.php
`'controllerMap'       => [

        'elfinder' => [
            'class'            => 'mihaildev\elfinder\Controller',
            //глобальный доступ к фаил менеджеру @ - для авторизорованных , ? - для гостей , чтоб открыть всем ['@', '?']
            // разрешаем радакторам, админам и супер админам
            'access'           => [
                \common\helpers\rbac\BaseRule::ROLE_EDITOR,
                \common\helpers\rbac\BaseRule::ROLE_ADMIN,
                \common\helpers\rbac\BaseRule::ROLE_SUPER_ADMIN,
            ],
            //отключение ненужных команд https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commands
            'disabledCommands' => ['netmount'],
            // корневые папки
            'roots'            => [
                // общая
                [
                    'baseUrl'  => '@web',
                    'basePath' => '@webroot',
                    'path'     => 'files/global',
                    'name'     => ['category' => 'elfinder', 'message' => 'Общая папка'],
                ],
                // свои для каждого пользователя
                [
                    'class' => 'mihaildev\elfinder\volume\UserPath',
                    'path'  => 'files/user_{id}',
                    'name'  => ['category' => 'elfinder', 'message' => 'Мои изображения'],
                ],
                // изображения категорий товаров
                [
                    'path' => 'files/product_categories',
                    'name' => ['category' => 'elfinder', 'message' => 'Категории продуктов'],
                ],
                // изображения товаров
                [
                    'path' => 'files/products',
                    'name' => ['category' => 'elfinder', 'message' => 'Продукты'],
                ],
                /*
                [
                    'path'   => 'files/some',
                    'name'   => ['category' => 'elfinder', 'message' => 'Some Name'], // Yii::t($category, $message)
                    'access' => ['read' => '*', 'write' => 'UserFilesAccess'] // * - для всех, иначе проверка доступа в даааном примере все могут видет а редактировать могут пользователи только с правами UserFilesAccess
                ],
                */
            ],
            'watermark'        => [
                'source'         => __DIR__ . '/water-mark.png', // Path to Water mark image
                'marginRight'    => 5,          // Margin right pixel
                'marginBottom'   => 5,          // Margin bottom pixel
                'quality'        => 95,         // JPEG image save quality
                'transparency'   => 70,         // Water mark image transparency ( other than PNG )
                'targetType'     => IMG_GIF | IMG_JPG | IMG_PNG | IMG_WBMP, // Target image formats ( bit-field )
                'targetMinPixel' => 200         // Target image minimum pixel size
            ],
        ],
    ],`

Потом прикручиваю Kartik Tree Manager:
index.php:
```
echo TreeView::widget([
    'id'               => 'product-category-tree',
    // single query fetch to render the tree
    'query'            => ProductCategory::find()->addOrderBy('root, lft, Name'),
    'nodeView'         => '@app/views/product-category/_form',
    'headingOptions'   => ['label' => 'Категории'],
    'rootOptions'      => ['label' => '<span class="text-primary">Категории</span>'],
    // this will override the headingOptions
    'topRootAsHeading' => true,
    'fontAwesome'      => true,
    // optional (toggle to enable admin mode)
    'isAdmin'          => User::isAdmin(),
    'iconEditSettings' => [
        'show'     => 'list',
        'listData' => [
            'folder' => Yii::t('app', 'Папка'),
            'file'   => Yii::t('app', 'Документ'),
            'gift'   => Yii::t('app', 'Тортик'),
            'bell'   => Yii::t('app', 'Колокольчик'),
        ],
    ],
    // initial display value
    'displayValue'     => 1,
    'showIDAttribute'  => false,
    // normally not needed to change
    'softDelete'       => false,
    // normally not needed to change
    'cacheSettings'    => ['enableCache' => false],
]);
```

Дальше, в форме:
```
echo $form->field($node, 'Description')->widget(CKEditor::className(),[
        'editorOptions' => [
            //разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
            'preset' => 'basic',
            //по умолчанию false
            'inline' => false,
            'editorOptions' => ElFinder::ckeditorOptions('elfinder',
                [/* Some CKEditor Options */]
            ),
        ],
    ]);
```

CKEditor отлично работает.

Одно недоразумение:
![image](https://user-images.githubusercontent.com/10991089/67059002-f0769080-f15f-11e9-9810-c801e8d74ddc.png)

Хотелось бы картинки, таки, выбирать...

Да, отдельно, если через iframe тот же контроллер прикручиваю, то всё гуд:
![image](https://user-images.githubusercontent.com/10991089/67059178-b5c12800-f160-11e9-8720-6f3b4a8d758f.png)

**Comment by MihailDev** [comment]
так и как решил??? или что было не так?

**Comment by mtc-toolbox** [comment]
> так и как решил??? или что было не так?

C namespace накосячил. Всё гуд.
