### ISSUE TITLE
404 elfinder

### ISSUE THREAD

**Issue by klyuko** [MihailDev/yii2-elfinder#136]
Буду очень благодарен если кто то подскажет почему получаю 404

**Подключение :** 

 ```
   $form->field($model, 'description')->widget(CKEditor::className(), [
        'editorOptions' => ElFinder::ckeditorOptions('elfinder',[]),
    ]); 
```

**Настройки urlManager :** 

        'urlManager' => [
            'class' => 'codemix\localeurls\UrlManager',
            'languages' => ['ru', 'en', 'uk'],
            'languageCookieDuration' => false,
            'enableLanguagePersistence' => false,
            'enableDefaultLanguageUrlCode' => true,
            'enableLanguageDetection' => false,

            'enablePrettyUrl' => true,
            'showScriptName' => false,

            'rules' => [
                '/' => 'site/index',
                'contact' => 'site/contact',
                'about' => 'site/about',
                'blog/' => 'blog/index',

                '<module:(admin|rbac)>/<controller:[\wd-]+>/<action:[\wd-]+>/<id:\d+>' => '<module>/<controller>/<action>',
                '<module:(admin|rbac)>/<controller:[\wd-]+>' => '<module>/<controller>',
                '<module:(admin|rbac)>' => '<module>',

            ],
        ],
    
     

**Настройки controllerMap :** 

    'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'access' => ['@'],
            'root' => [
                'baseUrl'=>'/web',
                'path' => 'uploads/global',
                'name' => 'Global'
            ],
        ]
    ],

**Comment by MihailDev** [comment]
скорее всего проблема в UrlManager
добавь туда правило для elfinder
`'elfinder/<a>' => 'elfinder/<a>'
`
на всяк проверь в дебаг логах кокой роуте в результате получается и какая ссылка вообще 

и на всяк эти правила у тебя не совсем верные
```
'<module:(admin|rbac)>/<controller:[\wd-]+>' => '<module>/<controller>',
'<module:(admin|rbac)>' => '<module>',
```
по идее должно быть 
```
'<module:(admin|rbac)>/<controller:[\wd-]+>' => '<module>/<controller>/index',
'<module:(admin|rbac)>' => '<module>/default/index',
```

а то если появится одноимённый контроллер будет тебе счастье

**Comment by klyuko** [comment]
> и на всяк эти правила у тебя не совсем верные
> 
> ```
> '<module:(admin|rbac)>/<controller:[\wd-]+>' => '<module>/<controller>',
> '<module:(admin|rbac)>' => '<module>',
> ```
> 
> по идее должно быть
> 
> ```
> '<module:(admin|rbac)>/<controller:[\wd-]+>' => '<module>/<controller>/index',
> '<module:(admin|rbac)>' => '<module>/default/index',
> ```
> 
> а то если появится одноимённый контроллер будет тебе счастье

Спасибо за правку правил


> скорее всего проблема в UrlManager
> добавь туда правило для elfinder
> `'elfinder/<a>' => 'elfinder/<a>' `
> на всяк проверь в дебаг логах кокой роуте в результате получается и какая ссылка вообще
> 

Спасибо, в логах нашел 
![image](https://user-images.githubusercontent.com/52352088/78974019-b340f900-7b19-11ea-8230-ba7ec4182e66.png)

**Comment by klyuko** [comment]
@MihailDev  Спасибо большое!
Для тех у кого будет подобное, исправил следующим образом:
 

1.  Добавил правило в UrlManager
`'elfinder/<a>' => 'elfinder/<a>'
`
2. Добавил `elfinder/*` в `as access` 

3. И будьте внимательные с `access` в `controllerMap`
