### ISSUE TITLE
watermark

### ISSUE THREAD

**Issue by smartbit45** [MihailDev/yii2-elfinder#139]
Здравствуйте! Использую elfinder второй день, видимо не до конца разобрался. Не могу найти как пользоваться watermark. 
мой конфиг:
`'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'access' => ['@'],
            'root' => [
                'path' => 'upload/images/global',
                'name' => 'Global'
            ],
            'watermark' => [
                'source'         => __DIR__.'/logo.png',
                'marginRight'    => 5,
                'marginBottom'   => 5,
                'quality'        => 95,
                'transparency'   => 70,
                'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP,
                'targetMinPixel' => 200
            ]
        ]
    ],`

Менеджером пользуюсь в админке:

`echo ElFinder::widget([
    'language'         => 'ru',
    'controller'       => 'elfinder',
    'path' => 'image',
    'filter'           => 'image',
    'callbackFunction' => new JsExpression('function(file, id){}'),
    'frameOptions' => [
            'style' => 'width: 100%; height: 90vh; border: 0;'
        ],
]);`

прошу прощения за кашу, но функция insert code почему то не работает как надо

**Comment by MihailDev** [comment]
'source' => __DIR__.'/logo.png' изображение имеет правильный путь?

**Comment by smartbit45** [comment]
Сам файл расположен по адресу корень проекта/web/upload/images/logo.png, в данный момент указал так
 'source' => 'upload/images/logo.png', но по прежнему пусто. выглядит после загрузки это так
[https://b.radikal.ru/b22/2007/07/b0d1d756fc4a.jpg](url)
А во время самой загрузки не происходит ничего. Контроллер не видит саму png, поэтому не предлагает её наложить?

**Comment by MihailDev** [comment]
https://prnt.sc/tf7xuv

**Comment by MihailDev** [comment]
'source' => '/web/upload/images/logo.png',  тут нужен полный путь

**Comment by smartbit45** [comment]
Сделал по аналогии
http://prnt.sc/tf8eju
не могу понять что упускаю, уже и пнг менял, думал битая
http://prnt.sc/tf8fh3

**Comment by MihailDev** [comment]
DIR - это у тебя скорее всего папка config
у тебя должен быть путь типа ` __DIR__ . '/../web/upload/logo.png' `

**Comment by smartbit45** [comment]
Слушай точно, спасибо! буду разбираться как так получилось. По идее сервер только в папку web же смотрит.

**Comment by MihailDev** [comment]
конфиги лежат папке config dir указывает путь к директории текущего фаила

**Comment by smartbit45** [comment]
Да, уже понял. Последний вопрос, как поместить марку на всё изображение, а не в угол?

**Comment by MihailDev** [comment]
тут все возможности плагина
https://github.com/Studio-42/elFinder/blob/master/php/plugins/Watermark/plugin.php
