### ISSUE TITLE
Загрузка картинок с админки в корень-загружает только в /admin

### ISSUE THREAD

**Issue by oxoooooo** [MihailDev/yii2-elfinder#148]
Подскажите пожалуйста как сделать загрузку с  формы установленной в backend не в backend/images а в frontend/images, не соображу где исправить?

манипуляции типа    'path' => '../frontend/web/images',  - создает и загружает в папку  admin/frontend/web/images. @frontend/images тоже получается

**Comment by MihailDev** [comment]
create alases ( https://www.yiiframework.com/doc/guide/2.0/ru/concept-aliases )
```
return [
    // ...
    'aliases' => [
        '@frontend' => '/path/to/frontend/web',
        '@frontendUrl' => 'https://www.frontend.com',
    ],
];

```

configure path

```
 [
    'baseUrl'=>'@frontendUrl',
    'basePath'=>'@frontend',
    'path' => 'images',
    'name' => 'Frontend Images'
],
```

**Comment by oxoooooo** [comment]
К сожалению так как Вы предложили не получается.  Путь формируется в PathController, пока не понял как переделать.
MihailDev не подскажите еще вариант как сделать?

**Comment by oxoooooo** [comment]
Выше приведенный способ 

common/config/main.php:
```
 'root' => [
                'baseUrl'=>'http://site',
                'basePath'=>'frontend/web',
                'path' => 'images',
                'name' => 'Images'
            ],
```
стал правильно выставлять путь на картинку в редакторе http://site/images/3.png, но картинку загружает в  http://site/backend/web/frontend/web/images/3.png

В Yii2 все просто, но с путями с вашим расширением что-то не очень получается... Заранее спасибо за подсказку.

**Comment by MihailDev** [comment]
basePath должен быть алиасом или абсолютным путём для того чтоб настройки работали верно!
думаю так должно сработать 'basePath'=>'@app/../frontend/web',

**Comment by MihailDev** [comment]
если вы исползаете [app-advanced](https://github.com/yiisoft/yii2-app-advanced) то можно и 'basePath'=>'@frontend/web',

**Comment by oxoooooo** [comment]
Спасибо! Все работает!
