### ISSUE TITLE
Failed to instantiate component or class "mihaildev\elfinder\ConnectorAction".

### ISSUE THREAD

**Issue by AzizbekIsmoilov** [MihailDev/yii2-elfinder#150]
I was customizing Elfinder Digital Ocean space and this problem appeared when I configured the config
![image](https://github.com/MihailDev/yii2-elfinder/assets/76866564/08476959-1842-48a2-acf7-231fb98bcdf4)

I made this config, can you help me with this solution

**Comment by asadbekkuz** [comment]
This issue is the same https://github.com/MihailDev/yii2-elfinder/issues/151#issue-1934377360
