### ISSUE TITLE
Problem with Digital Ocean Space server

### ISSUE THREAD

**Issue by asadbekkuz** [MihailDev/yii2-elfinder#151]
HI Mihail, how can I integrate elfinder with digital ocean. I've seen the configurations integerate aws server, but it has not digital ocean. Do you help me ? Please answer me

**Comment by MihailDev** [comment]
https://github.com/MihailDev/yii2-elfinder-flysystem/

https://github.com/creocoder/yii2-flysystem#aws-s3-filesystem

https://docs.digitalocean.com/products/spaces/reference/s3-sdk-examples/

вт, 10 окт. 2023 г. в 08:06, Asadbek Sotqinboyev ***@***.***>:

**Comment by asadbekkuz** [comment]
thank you, so  much
