### ISSUE TITLE
оптимизация работы с настройками папок

### ISSUE THREAD

**Issue by MihailDev** [MihailDev/yii2-elfinder#16]
на основе запроса #15 

есть предложенеи о передаче настроек в виде параметра в ссылке но опять же возникает множество вопросов как лучеш это сделать:
мне видется один из вариантов такой
при настройке папок выдавать им идентификаторы
тогда можно передавать идентификатор и допустим какойто внутренний путь чтот типа такого
elfinder?id=articles&folder=sub/folder/in/articles

то есть получаем настройки для идентификатора articles и добавляем в него под папку sub/folder/in/articles тогда допустим при редактировании статей в мэнеджере откроется не весь список доступных папок а именно указанная

**Comment by twg-group** [comment]
Научи, пожалуйста, как подключиться к удалённой папке по FTP, тут такое дело, что админка отдельно хостится от сайта....

**Comment by twg-group** [comment]
По вашему сабжу, сделайте default папку по имени модуля/контроллера из которого вызывается виджет, например из модуля news - сразу по дефолту в news (ну или news/controller/action)... либо через настройки виджета (глобального конфига)... короче по типу view файлов, у вас должен по сути быть классический роутинг yii... тогда, как минимум всем будет всё понятно... наверно...
