### ISSUE TITLE
Как включить crop,resize,rotation?

### ISSUE THREAD

**Issue by pavlinter** [MihailDev/yii2-elfinder#18]
Настройки по умолчанию , а resize,crop,rotation выключеные радио кнопки

**Comment by pavlinter** [comment]
Если не сделать в контроллере свойство, которое будет включать noConflict, то и нет смысла Assets::noConflict($this);, так как мне все равно надо будет заменять views/manager.php что бы вызвать там Assets::noConflict($this);

**Comment by MihailDev** [comment]
а зачем вам заменять views/manager.php ведь он как раз для генерации во фрейме конфликт происходит при интеграции непосредственно в страницу без фрейма по сути вы пишите шаблон знаете что там будет bootstrap и \mihaildev\elfinder\Assets::noConflict($this); и всё ок! 
или я что то не понимаю?

**Comment by pavlinter** [comment]
Есть плагин который не зависит от вашего плагина. Этот плагин использует событие endBody, там и подргужается bootstrap скрипты.Свою ситуацию я могу решить так:
<pre>
'class' => 'mihaildev\elfinder\Controller',
'on beforeAction' => function ($event) {
    Yii::$app->getView()->off('endBody');
},
</pre>
Если вдуматься,а что если другие плагины будут использовать события которые находятся в views/manager.php и использовать там bootstrap?! Людям, которые используют этот плагин будут делать как и я.
Есть пару предложений: 
1) Вызывать \mihaildev\elfinder\Assets::noConflict($this); в views/manager.php.
Этим самым мы не подгружаем bootstrap и решаем конфликт
2) Удалить события в views/manager.php, что думаю не совсем правельно.

**Comment by MihailDev** [comment]
возможно вы имеете ввиду доп плагины к самому мэнеджеру то есть в открывшемся фрейме запускается плагин который подтягивает bootstrap? я вас правильно понял?

**Comment by pavlinter** [comment]
да
