### ISSUE TITLE
PathController и относительные пути

### ISSUE THREAD

**Issue by loveorigami** [MihailDev/yii2-elfinder#23]
Настроил PathController.
Все работает.
Начал проводить известные приемы ).
1. Подключил к папке @web/uploads
2. Path в виджете указал images
3. Отобразилось все в iframe
4. Открыл iframe в отдельном окне
5. написал в адресной строке site.ru/elfinder/manager?lang=ru&path=../../../
6. получил доступ к корню всего проекта

-----------
нужна проверка - есть ли в path относительный путь (..) и закрывать доступ, если есть.
А лучше даже закодировать путь (mcrypt_encrypt + salt из конфига)

p.s. никак не могу понять, как подключить FM без iframe, чтобы там "поэксперементировать"
в инструкции только сказано, как избавиться от конфликта с bootstrap.js...

**Comment by loveorigami** [comment]
чтоб исправить замечание, правим тут
https://github.com/MihailDev/yii2-elfinder/blob/master/PathController.php#L69
на
```php
        if(!empty($subPath)){
            if(preg_match("/\./i", $subPath)){
                $root['path'] = rtrim($root['path'], '/');
            }
            else{
                $root['path'] = rtrim($root['path'], '/');
                $root['path'] .= '/' . trim($subPath, '/');
            }
        }
```

**Comment by MihailDev** [comment]
клёвое решение я как то до этого не допёр сделаю я вообше хотел немного переработать и сделать более расширяемый но проблема в суб патхе и куча основной работы меня затормозили! спс!

**Comment by MihailDev** [comment]
исправил
