### ISSUE TITLE
connect FTP server

### ISSUE THREAD

**Issue by twg-group** [MihailDev/yii2-elfinder#29]
How to?

**Comment by MihailDev** [comment]
Я вот добавил фтп класс ток чтот он на тестах у меня загнулся 
постоянно вылазит ошибка фаил не найден
получилос загрузить файло на фтп и просмотреть удалить изменить никак пока не потдаётся
настройки следуюшие
```php
'roots' => [
				[
					'class' => 'mihaildev\elfinder\FtpPath',
					'baseUrl' => 'http://test.com/',
					'basePath' => '/public_html/',
					'path' => 'test/',
					'host' => '******',
					'user' => '******',
					'pass' => '******',
					'name' => 'Test Ftp',
				],
			]
```

**Comment by loveorigami** [comment]
сталкивался с похожим.
на моем хостинге нужно было добавить файл .ftpaccess и в нем разрешить выполнение операций с определенного ip.

```
<Limit Write>
Allow xxx.xxx.0.0/18 # you ip
DenyAll
</Limit>
```

**Comment by MihailDev** [comment]
если не сложно потестируй данный класс у себя если всё работает то эт супер!

**Comment by twg-group** [comment]
Да, я немного переделал LocalPath.php та же проблема была, выяснялось что всё дело в параметрах:
<pre>
'tmbPath'       => '/',
'tmpPath'       => '/',
</pre>

Если этих параметров нету либо неверно сконфигурированы, то на сервак не залогиниться.

полный конф:

<pre>        
$options=[          
            'driver'        => 'FTP',
            'host'          => '***.ru',
            'user'          => 'user',
            'pass'          => 'pswd',
            'port'          => 21,
            'mode'          => 'passive',
            'path'          => '/',
            'URL'           => 'http://***.ru/uploads',
            'timeout'       => 10,
            'owner'         => true,
            'tmbPath'       => '/',
            'tmpPath'       => '/',
            'dirMode'       => 0777,
            'fileMode'      => 0777,
        ];
</pre>

Всё подключается фалы перекидываются, единственная проблема с миниатюрами картинок (tmb), не понимаю почему, но их нет...

**Comment by CSPutera** [comment]
Hello, Im having the same difficulties in connecting to FTP. Tried to follow above instructions but dont quite understand the language. Could you please help re-explaining in English ? Thank you very much.

**Comment by MihailDev** [comment]
now via FTP icons not work
on the weekend I try to solve the problem

if you have problems with installation write me

Example of FTP connection

```php
[
					'class' => 'mihaildev\elfinder\FtpPath',
					'baseUrl' => 'http://domain.com/', //url to ftp path
					'basePath' => '/public_html/', //ftp path
					'path' => 'test/', //path in ftp path (real path will be  /public_html/test/, real Url will be http://domain.com/test/)
					'host' => 'ftp.domain.com',
					'user' => 'ftp_username',
					'pass' => 'ftp_password',
					'name' => 'Root Name',
				],
```
ps. Sorry for my English

**Comment by CSPutera** [comment]
Hi, thank you so much for the fast response. Im trying to debug the problem, I get error 500 from server each time I try to access the files. It goes to : /web/elfinder/connect, may I know where exactly is that request pointing to ? I try to find in \mihaildev\yii2-elfinder\Controller.php, but I find no actions there. Please help, thank you.

**Comment by MihailDev** [comment]
show your config file

**Comment by MihailDev** [comment]
Now there are 2 variants settings
1) multiple paths (mihaildev\elfinder\Controller)
2) one path (mihaildev\elfinder\PathController)

actions in BaseController

**Comment by CSPutera** [comment]
Hello. Sorry for the late reply. This is my config : 
 'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\Controller',
            'access' => ['@'], //глобальный доступ к фаил менеджеру @ - для авторизорованных , ? - для гостей , чтоб открыть всем ['@', '?']
            'disabledCommands' => ['netmount'], //отключение ненужных команд https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commands
            'roots' => [
                [
                    'class' => 'mihaildev\elfinder\FtpPath',
                    'baseUrl' => 'http://onmol.mo***.com',
                    'basePath' => '/var/www/vhosts/mo***.com/onmol.mo***.com/',
					'path'  => 'web/uploads/',
					'host' => 'onmol.mo***.com',
                    'user' => '***',
                    'pass' => '***',
                    'name'  => 'My Documents'
                ],
            ],
            'watermark' => [
                'source'         => __DIR__.'/logo.png', // Path to Water mark image
                'marginRight'    => 5,          // Margin right pixel
                'marginBottom'   => 5,          // Margin bottom pixel
                'quality'        => 95,         // JPEG image save quality
                'transparency'   => 70,         // Water mark image transparency ( other than PNG )
                'targetType'     => IMG_GIF|IMG_JPG|IMG_PNG|IMG_WBMP, // Target image formats ( bit-field )
                'targetMinPixel' => 200         // Target image minimum pixel size
            ]
        ]
    ],

**Comment by MihailDev** [comment]
config file looks OK, but not sure whether you have specified the path (/var/www/vhosts/mo.com/onmol.mo.com/) it look like a absolute path and not as a way of FTP

error 500 is from server or from framework?
Show log yii or server?

**Comment by CSPutera** [comment]
Yuph, checking on the server, got err "Connection reset by peer: mod_fcgid: error reading data from FastCGI server", I guess it's from the server side. Will update you soon, thank you so much for your support.

**Comment by CSPutera** [comment]
Hello. Can I use this to manage files on AWS ? If can, could you please kindly show me how to achieve this ? Thank you

**Comment by MihailDev** [comment]
AWS this is "elFinder driver for Amazon S3 (SOAP) filesystem."?

**Comment by CSPutera** [comment]
Yes, I'd like to save the files on Amazon S3 instead on my local drive. Can I use this extension to do that ? Sorry for not being detail before.

**Comment by MihailDev** [comment]
I added a class (mihaildev\elfinder\S3Path) but can not test!
there is no money on a visa card can not create a test account

```php
[
					'class' => 'mihaildev\elfinder\S3Path',
					'name' => 'S3',
					'accessKey' => '*****',
					'secretKey' => '*****',
					'bucket' => '*****',

				],
```

**Comment by jasneet-bhatia** [comment]
can i used ftp without giving details of ftp in elfinder if elfinder on same server

**Comment by MihailDev** [comment]
if server same why you use ftp?
