### ISSUE TITLE
callbackFunction option error

### ISSUE THREAD

**Issue by mafeifan** [MihailDev/yii2-elfinder#31]
Unknown Property – yii\base\UnknownPropertyException

Setting unknown property: mihaildev\elfinder\InputFile::callbackFunction
<?php
$elfinderConfig = [
    'language'   => 'zh_CN',
    'controller' => 'elfinder', 
    'filter'     => 'image',  
    'template'      => '{button}',
    'options'       => ['class' => 'form-control'],
    'buttonOptions' => ['class' => 'btn btn-default'],
    'path' => '',
    'multiple' => 1,
    'callbackFunction' => new JsExpression('function(file, id){ console.dir(file);}')  // add this line cause error

**Comment by MihailDev** [comment]
InputFile widget don`t have property callbackFunction
As I understood you need a button with callback function

At the moment there is no widget buttons but I will soon!
Now you can do
```php

/** @var \yii\web\View $this */



mihaildev\elfinder\AssetsCallBack::register($this);

$buttonOptions = [
	'id' => 'el_button'
];

echo \yii\helpers\Html::tag('button', 'Browse', $buttonOptions);

$managerOptions = [];
$managerOptions['language'] = 'zh_CN';
$managerOptions['filter'] = 'image';
$managerOptions['path'] = 'path';
$managerOptions['callback'] = 'el'; //manager ID

$managerOptions['url'] = \mihaildev\elfinder\ElFinder::getManagerUrl('elfinder', $managerOptions);
$managerOptions['width'] = 'auto';
$managerOptions['height'] = 'auto';
$managerOptions['id'] = $managerOptions['callback'];

$this->registerJs("mihaildev.elFinder.register(" . \yii\helpers\Json::encode($managerOptions['id']) . ", function(file, id){ console.dir(file); return true;});"); // register callback Function
$this->registerJs("\$(document).on('click', '#" . $buttonOptions['id'] . "', function(){mihaildev.elFinder.openManager(" . \yii\helpers\Json::encode($managerOptions) . ");});");//on click button open manager

```

ps. Sorry for my English

**Comment by mafeifan** [comment]
thanks very much. you solve my problem.  my English is not very good too.  :smile:
