### ISSUE TITLE
Access in PathController

### ISSUE THREAD

**Issue by loveorigami** [MihailDev/yii2-elfinder#34]
Михаил, подскажите, как указать права доступа в PathController по операциям. Как в Вашем примере для 'mihaildev\elfinder\Controller'
```php
                [
                    'path'   => 'files/some',
                    'name'   => ['category' => 'my','message' => 'Some Name'], // Yii::t($category, $message)
                    'access' => ['read' => '*', 'write' => 'UserFilesAccess'] // * - для всех, иначе проверка доступа в даааном примере все могут видет а редактировать могут пользователи только с правами UserFilesAccess
                ]
```
вставлял блок в разные места, пробовал разные комбинации... все равно могу редактировать, загружать и удалять...

**Comment by MihailDev** [comment]
я тестировал 
мои настройки
```php
				[
					'path' => 'files/global',
					'name' => 'Global',
					'access' => ['read' => '*', 'write' => 'testNoAccess']
				],
```
папка была доступна только для чтения

как работают права если указываете какое то значение отличное от *  то происходит проверка
Yii::$app->user->can($this->access['write'])

вот полный механизм получения прав доступа
```php
    public function getDefaults(){
        if($this->_defaults !== null)
            return $this->_defaults;
        $this->_defaults['read'] = false;
        $this->_defaults['write'] = false;
		

        if(isset($this->access['write'])){
            $this->_defaults['write'] = true;
            if($this->access['write'] != '*'){
                $this->_defaults['write'] = Yii::$app->user->can($this->access['write']);
            }
        }

        if($this->_defaults['write']){
            $this->_defaults['read'] = true;
        }elseif(isset($this->access['read'])){
            $this->_defaults['read'] = true;
            if($this->access['read'] != '*'){
                $this->_defaults['read'] = Yii::$app->user->can($this->access['read']);
            }
        }

        return $this->_defaults;
    }
```

**Comment by MihailDev** [comment]
я подозреваю что на вашем проекте вы авторизируетесь как царь и бог и имеете все права поэтому у вас есть доступ!

**Comment by loveorigami** [comment]
Да нет, под admin - у меня работает. Захожу под ограниченной записью - права не работают......
вот мой конфиг.
Использую я PathController
```php
   'controllerMap'=>[
        'elfinder' => [
            'class' => '\mihaildev\elfinder\PathController',
            //'access' => ['admin'], //глобальный доступ к фаил менеджеру @ - для авторизорованных , ? - для гостей , чтоб открыть всем ['@', '?']
            'disabledCommands' => ['netmount'], //отключение ненужных команд https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commands
            'root' => [
                'baseUrl' => '@storageUrl',
                'basePath' => '@storage',
                'access' => ['read' => '*', 'write' => 'UserFilesAccess'],
                'name' => ['category' => 'backend', 'message' => 'Category'], // Yii::t($category, $message)
                'options' => [
                    'tmbSize' => '48',
                    'acceptedName' => '/^[0-9a-z_\-.]+$/i', // i любой регистр только англ
                    'imgLib' => 'gd',
                    'attributes' => [
                        [
                            'pattern' => '!^/test!',
                            'read' => true,
                            'locked' => true,
                            'write' => false,
                            'hidden' => false,
                        ],
                    ]
                ]
            ]
        ]
    ],
```
для папки тест разрешения работают. 
а вот для корневой - нет.

![001](https://cloud.githubusercontent.com/assets/98164/8076030/9e069f04-0f58-11e5-9285-c324e252d9fd.jpg)

В BasePath исправил
```php
  public function getDefaults(){

        $this->_defults['read'] = true;
        $this->_defults['write'] = false;

        return $this->_defults;
    }
```
все так же могу записывать...
ставлю $this->_defults['read'] = false; - получаю - ошибку для чтения... т.е права работают.
а при $this->_defults['write'] = false; - файлы записываются...

**Comment by MihailDev** [comment]
```php
'controllerMap' => [
		'elfinder' => [
			'class' => '\mihaildev\elfinder\PathController',
			//'access' => ['admin'], //глобальный доступ к фаил менеджеру @ - для авторизорованных , ? - для гостей , чтоб открыть всем ['@', '?']
			'disabledCommands' => ['netmount'], //отключение ненужных команд https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commands
			'root' => [
				'baseUrl' => '/files/global',
				'basePath' => '@webroot/files/global',
				'access' => ['read' => '*', 'write' => 'UserFilesAccess'],
				'name' => 'Name', // Yii::t($category, $message)
				'options' => [
					'tmbSize' => '48',
					'acceptedName' => '/^[0-9a-z_\-.]+$/i', // i любой регистр только англ
					'imgLib' => 'gd',
					'attributes' => [
						[
							'pattern' => '!^/test!',
							'read' => true,
							'locked' => true,
							'write' => false,
							'hidden' => false,
						],
					]
				]
			]
```

![yii2-elfinder libs ru 2015-6-10 12 57 19](https://cloud.githubusercontent.com/assets/2392194/8079903/7d47f19c-0f70-11e5-9991-cd50363461b6.png)

**Comment by loveorigami** [comment]
магтя какая то...))).
возможно, из-за того, что я права доступа проверяю, как событие из конфига...
```php
    'as access' => [
        'class' => 'mdm\admin\components\AccessControl',
        'allowActions' => [
            'site/error',
            'user/security/login',
            'user/security/logout'
        ]
    ],
'components' => [
.......
],
```
пункты меню, доступ к модулям, доступ к операциям - все настраивается и работает...
но с другой стороны - я же принудительно ставлю
```php
        $this->_defults['read'] = true;
        $this->_defults['write'] = false;
```
и все равно могу записывать файлы. RBAC вообще тут не причем, получается...
тестировал под win7(x86 и x64)

на запись в корне ограничил пока через опции
```php
                'options' => [
                    //'driver'	 => 'LocalFileSystem',
                    'tmbSize' => '48',
                    'acceptedName' => '/^[0-9a-z_\-.]+$/i', // i любой регистр только англ
                    'imgLib' => 'gd',
                    'attributes' => [
                        [
                            'pattern' => '!^/$!',
                            'read' => true,
                            'locked' => false,
                            'write' => false,
                            'hidden' => false,
                        ],
                        [
                            'pattern'	 => '!^/(test|123)!',
                            'hidden'	 => false,
                            'write' => false,
                        ],
                    ]
                ]
```
так получилось, как у вас на скриншоте )

**Comment by loveorigami** [comment]
Михаил, прошу прощения. 
в композере стояло "mihaildev/yii2-elfinder": "^1.0",
думал, будет скачивать все версии, выше первой...
поставил "mihaildev/yii2-elfinder": "^1.0", - все работает!

**Comment by loveorigami** [comment]
Продолжу тему.
Только что натолкнулся на ошибку.

Есть базовый конфиг
```
....
        'elfinder' => [
            'class' => '\mihaildev\elfinder\PathController',
            'access' => ['admin'], 
            'root' => [
                'baseUrl' => '/files/global',
                'basePath' => '@webroot/files/global',
                'access' => ['read' => '*', 'write' => 'admin'],
            ]
...
```

и локальный в модуле, который мержится с основным.
В одном модуле хочу дать доступ на запись менеджеру

```
        'elfinder' => [
            'access' => ['manager'], 
            'root' => [
                'access' => ['read' => '*', 'write' => 'manager'],
            ]
```

и после объединения конфигов менеджер не может загрузить фото.

если же закомментировать в базовом конфиге строку
```
  'access' => ['read' => '*', 'write' => 'admin'],
```
то все работает...

**Comment by loveorigami** [comment]
может из-за того, что получаем в результате
```
    'elfinder' => array (3) [
        'class' => string (34) "\mihaildev\elfinder\PathController"
        'access' => array (2) [
            string (5) "admin", 
            string (7) "manager"
        ]
        'root' => array (3) [
            'baseUrl' => string (13) "/files/global"
            'basePath' => string (21) "@webroot/files/global"
            'access' => array (2) [
                'read' => string (1) "*"
                'write' => string (7) "manager"
            ]
        ]
    ]

```

**Comment by MihailDev** [comment]
`
elfinder' => array (3) [
        'class' => string (34) "\mihaildev\elfinder\PathController"
        'access' => array (2) [ // данный настройка задумывалась как минимальный доступ по идее тут должен быть доступ для всех (это настройка доступа к самому контролеру)
        ]
        'root' => array (3) [
            'baseUrl' => string (13) "/files/global"
            'basePath' => string (21) "@webroot/files/global"
            'access' => array (2) [
                'read' => string (1) "*"
                'write' => string (7) "manager" // данный настройка задумывалась как проверка доступа к определённой папке
            ]
        ]
    ]
`

**Comment by livej0urnal** [comment]
Добрый день. Подскажите как настроить загрузку в корневую папку другого поддомена.

**Comment by MihailDev** [comment]
elfinder' => array (3) [
        'class' => string (34) "\mihaildev\elfinder\PathController"
        'access' => array (2) [ // данный настройка задумывалась как минимальный доступ по идее тут должен быть доступ для всех (это настройка доступа к самому контролеру)
        ]
        'root' => array (3) [
            'baseUrl' => string (13) "https://some.example.com/files/global"
            'basePath' => string (21) "@some.example/files/global"
            'access' => array (2) [
                'read' => string (1) "*"
                'write' => string (7) "manager" // данный настройка задумывалась как проверка доступа к определённой папке
            ]
        ]
    ]

**Comment by livej0urnal** [comment]
Данный пример не решает проблему. 
Я опишу ситуацию подробнее.
Существует два приложения, они находятся на одном хостинге но в разных корневых директориях.
1) Основной сайт
2) Админка
И задача в том чтобы можно было корректно редактировать с админки карточки товара. А для этого нужно загружать файлы в корневую другого сайта по сути.
