### ISSUE TITLE
Source code indentation problem

### ISSUE THREAD

**Issue by hightman** [MihailDev/yii2-elfinder#35]
Hi, I found there are many indentation problems in source code.

Mix of TAB and white-space, lead to misaligned,hope that the author can fix it, thanks.

**Comment by MihailDev** [comment]
Please select a file for example, or a piece of code

**Comment by hightman** [comment]
1.  [Asset.php](https://github.com/MihailDev/yii2-elfinder/blob/master/Assets.php): line40 ~ 47
2. [BasePath.php](https://github.com/MihailDev/yii2-elfinder/blob/master/BasePath.php): line27, line73~84, 
3. [Controller.php](https://github.com/MihailDev/yii2-elfinder/blob/master/Controller.php): line 52~66
4. [ELFinder.php](https://github.com/MihailDev/yii2-elfinder/blob/master/ElFinder.php): line 28, line 36, line 42~49, line 70~74, line 90~95, ...

... There are many other places ...

You can use an IDE (i.e: netbeans, vim) format them.


Sorry for another problem, whether to consider about upgrading elFinder library to latest version?

**Comment by MihailDev** [comment]
Now version installed 2.0-rc1 https://github.com/Studio-42/elFinder/releases

**Comment by hightman** [comment]
That release is too old, you can download the nightly snapshot from:

http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip <http://nao-pon.github.io/elFinder-nightly/latests/elfinder-2.1.zip>


This version has a powerful improvement, we can specify the start directory via `window.location.hash`. You can integrat into `ELFinder::$ path`, now this property has not any effects.




Best Regards

hightman/海鳗
**********************************
微信/微博：hightman
Github：https://github.com/hightman
