### ISSUE TITLE
to set basUrl and basePath

### ISSUE THREAD

**Issue by rahulk-k** [MihailDev/yii2-elfinder#39]
Hi, 
I am using yii2 advanced template. i can access http://localhost/devtuts 
and http://localhost/devtuts/backend.I have configured controllerMap  in backend/main.php
like this
'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'access' => ['@'],
            'root' => [
                'baseUrl'=>'@web',
                'basePath'=>'@webroot',
                'path' => 'files',
                'name' => 'Files'
            ],
    ...
My question is how can i set baseUrl and basePath by which i can store files inside 
http://localhost/devtuts/files folder from backend to frontend

**Comment by MihailDev** [comment]
'controllerMap' => [
'elfinder' => [
'class' => 'mihaildev\elfinder\PathController',
'access' => ['@'],
'root' => [
'baseUrl'=>'/devtuts/backend',
'basePath'=>'@app/backend', //full path to backend webroot
'path' => 'files',
'name' => 'Files'
],
