### ISSUE TITLE
Проблемы с подключением в модуле

### ISSUE THREAD

**Issue by porcelanosa** [MihailDev/yii2-elfinder#44]
Я подключила ElFinder к вашему же расширению CKEditor в модуле admin
```php

	<? echo $form->field($model, 'descr')->widget(CKEditor::className(), [
		'editorOptions' => ElFinder::ckeditorOptions('elfinder',[
			'preset' => 'full',
			//разработанны стандартные настройки basic, standard, full данную возможность не обязательно использовать
			'inline' => false,
			//по умолчанию false
		]),
	]); ?>
```
все работает.
но при вызове файлового менеджера возникает ошибка 404
Проблема связана с UrlManager 
Ведь когда я оставляю стандартные правила - 
```php
'<_c:[\w\-]+>/<id:\d+>' => '<_c>/view',
					'<_c:[\w\-]+>' => '<_c>/index',
					'<_c:[\w\-]+>/<_a:[\w\-]+>/<id:\d+>' => '<_c>/<_a>',
```
то всё работает.
А если я заменяю на правила для модульной структуры, то возникает вышеупомянутая ошибка
```php

					'<_m:[\w\-]+>/<_c:[\w\-]+>/<id:\d+>' => '<_m>/<_c>/view',
					'<_m:[\w\-]+>/<_c:[\w\-]+>/<_a:[\w\-]+>/<id:\d+>' => '<_m>/<_c>/<_a>',
					'<_m:[\w\-]+>' => '<_m>/default/index',
					'<_m:[\w\-]+>/<_c:[\w\-]+>' => '<_m>/<_c>/index',
```

Возможно это можно исправить как то в настройках подключения ElFinder ?

**Comment by porcelanosa** [comment]
Может как то настроить можно путь подключения?

**Comment by porcelanosa** [comment]
Вопрос снят.
для использование в модуле ControllerMap надо и прописывать для модуля.
Вот так:
```php

	'modules' => [
		'main' => [
			'class' => 'app\modules\main\Module',
		],
		'admin' => [
			'class' => 'app\modules\admin\Module',
			'controllerMap' => [
				'elfinder' => [
					'class' => 'mihaildev\elfinder\Controller',
					'access' => ['@'],
					'disabledCommands' => ['netmount'],
					'roots' => [
						[
							'baseUrl' => '@web',
							'basePath' => '@webroot',
							'path' => 'uploads',
							'name' => 'Файлы'
						]
					]
				]
			],
		],
		'user' => [
			'class' => 'app\modules\user\Module',
		],
	],
```

**Comment by Isuhi** [comment]
У меня возникла такая же проблема. Но я решил все-таки "добить" правила urlManager, чтобы выяснить подробности этих противоречий. Через пару часов выяснилось, что конфликтует только одно правило:
`'<_m:[\w\-]+>/<_c:[\w\-]+>' => '<_m>/<_c>/index',`
Я это правило закомментировал, а после вообще удалил, так как несколько вариантов его применения у меня были расписаны более подробно, и по сути оно и было лишним.
Elfinder подключил так:
`	 'components' => [
										. . .
    ],
		'controllerMap' => [
			'elfinder' => [
					'class' => 'mihaildev\elfinder\Controller',
					'access' => ['.....'],
					'roots' => [
							[
									'baseUrl' => '/web',
									'path' => '......',
									'name' => '......'
							]
					]
				]
		],
    'params' => $params,`
Все работает.
Кстати, пробовал подключать редактор в модуле по вашему примеру - не прошел номер. Видимо, у нас файловая структура разная.
Попробовал понять, почему же это правило конфликтовало с редактором - не осилил, плюнул - работает, да и ладно. Вот такие дела.

**Comment by MihailDev** [comment]
данное правило конфликтовало потому что когда формировалась ссылка тип elfinder/action
урлМанаджер её распозновал как  elfinder/action/index
то есть приложение не обращалось к контроллеру  elfinder а пыталось найти модуль elfinder с контроллером action и запустить в нём actionIndex

**Comment by Isuhi** [comment]
Понятно теперь, спасибо за пояснение.
