### ISSUE TITLE
Unable to resolve the request: elfinder/sounds/rm.wav

### ISSUE THREAD

**Issue by mgrechanik** [MihailDev/yii2-elfinder#45]
Hi.
I am working with pretty urls on and using InputFile::widget 
When I delete file from elfinder modal window I got into logs the next error:

'yii\base\InvalidRouteException' with message 'Unable to resolve the request: elfinder/sounds/rm.wav' in C:\WWW\htdocs\yii_mywebsite\vendor\yiisoft\yii2\base\Controller.php:122

**Comment by ComradePashka** [comment]
yep, I also use pretty URL and got same error, just one remark - however file rm.wav was successfully created at asset folder:
  @webroot\assets\XXXXXX\sounds

**Comment by alexantr** [comment]
It's old elFinder problem. Path to rm.wav hardcoded in javascript:
```js
// ...
.bind('rm', function(e) {
    var play  = beeper.canPlayType && beeper.canPlayType('audio/wav; codecs="1"');
    play && play != '' && play != 'no' && $(beeper).html('<source src="./sounds/rm.wav" type="audio/wav">')[0].play()
})
// ...
```
You have only one way. You can set right path in `elfinder.full.js` or `elfinder.min.js` manually.

**Comment by alexantr** [comment]
In new version (2.1.7) you can set `soundPath`. Need plugin updates.
