### ISSUE TITLE
thumbnails size

### ISSUE THREAD

**Issue by ComradePashka** [MihailDev/yii2-elfinder#46]
Is it possible to configure some way thumbnail images size and/or create few different size versions of images?
ElFinder itself has config value 'tmbSize' but I can't realize how to set it up via yii2-elfinder extention.
saving thumbnails not in asset (sub)folders and managing them also will be great!
TIA

**Comment by MihailDev** [comment]
'tmbSize'

```php
[
    'baseUrl'=>'@web',
    'basePath'=>'@webroot',
    'path' => 'files/global',
    'name' => 'Global',
    'options' => [
        'tmbSize' => '...',
    ]
]
```

'tmbPath' 

```php
[
    'baseUrl'=>'@web',
    'basePath'=>'@webroot',
    'path' => 'files/global',
    'name' => 'Global',
    'tmbPath' => 'some/web/folder', //dont work with alias or full path. see https://github.com/MihailDev/yii2-elfinder/blob/master/BasePath.php#L74
    
]
```
OR use raw

```php
[
    'baseUrl'=>'@web',
    'basePath'=>'@webroot',
    'path' => 'files/global',
    'name' => 'Global',
    'options' => [
        'tmbPath' => 'full/path/no/alias',
        'tmbURL' => 'full/path/no/alias',
    ]
]
```

"few different size versions" - no standard possibility to create multiple thumbnail

**Comment by ComradePashka** [comment]
Thanks a lot, Mihail!

tmbSize works fine, but setting tmbPath led to folder creation but thumbnails itself won't be created. and inside connect action handler responses there is missed attribute tmb comparing to normal asset-thumbs, so there are sort of default thumb (with small panda image) instead of normal thumbs inside
![image](https://cloud.githubusercontent.com/assets/15798005/11742837/ee365fc2-a013-11e5-9dd3-8d2ae7334366.png)

and in second case when passing tmbPath and tmbURL inside options - it seems to be ignored at all.
