### ISSUE TITLE
iframe unable to find jquery-ui

### ISSUE THREAD

**Issue by con322** [MihailDev/yii2-elfinder#48]
I get the following error within the iframe

The file or directory to be published does not exist: /Applications/MAMP/htdocs/advanced_4/_protected/vendor/bower/jquery-ui

Could you shed any light on why I may be getting this error/how to fix it?

Thanks :)

**Comment by MihailDev** [comment]
Update composer-asset-plugin
composer global require "fxp/composer-asset-plugin:~1.1.1"

I had a similar problem, the files are not stored in the folder "vendor/bower" and saved in the folder "vendor / bower / bower-assets"
