### ISSUE TITLE
Class 'Phar' not found

### ISSUE THREAD

**Issue by Linthm** [MihailDev/yii2-elfinder#49]
Помогите разобраться пож.
вот мои настройки 
<pre>
'controllerMap'=>[
        'elfinder' => [
            'class' => '\mihaildev\elfinder\PathController',
            'access' => ['@', '?'], //глобальный доступ к фаил менеджеру @ - для авторизорованных , ? - для гостей , чтоб открыть всем ['@', '?']
            'disabledCommands' => ['netmount'], //отключение ненужных команд https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#commands
            'root' => [
                'baseUrl' => '../',
                'basePath' => '@webroot',
                'path' => 'files/',
            ]
        ]
    ]
</pre>

 В результате получаю вот такую ошибку

<pre>
1. in /home/tvmecykf/new/vendor/mihaildev/elfinder/volume/aws.phar at line 17
891011121314151617181920212223242526 *
 * http://aws.amazon.com/apache2.0
 *
 * or in the "license" file accompanying this file. This file is distributed
 * on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing
 * permissions and limitations under the License.
 */
 
Phar::mapPhar('aws.phar');
 
define('AWS_PHAR', true);
 
require_once 'phar://aws.phar/vendor/symfony/class-loader/Symfony/Component/ClassLoader/UniversalClassLoader.php';
 
$classLoader = new Symfony\Component\ClassLoader\UniversalClassLoader();
$classLoader->registerNamespaces(array(
    'Aws'      => 'phar://aws.phar/src',
    'Guzzle'   => 'phar://aws.phar/vendor/guzzle/guzzle/src',
</pre>

Url: ../elfinder/connect?path=image&_csrf=NmtDZlRDVi1sPAorGQQgcgcBLgsFdRhGVF4HERUCGG8HPDISEnQyTg%3D%3D&mimes%5B%5D=image&cmd=open&target=&init=1&tree=1&_=1453123595408

**Comment by MihailDev** [comment]
скорее всего на сервере не хватает phar расширения

**Comment by Linthm** [comment]
Сейчас все корректно работает, но чтобы все заработало, пришлось убрать 
<pre>
require_once "aws.phar";
</pre>
в файле ../mihaildev/elfinder/volume/elFinderVolumeS3.class.php

**Comment by MihailDev** [comment]
в этом и проблема у вас на сервере не работает  phar
эта либа для работы с амазон облаком думаю вам не надо
