### ISSUE TITLE
Remove special characters and utf8

### ISSUE THREAD

**Issue by tuannda** [MihailDev/yii2-elfinder#51]
How to remove special example @#$%

and convert ảnh đẹp tự nhiện.jpg to anh-dep-tu-nhien.jpg

**Comment by MihailDev** [comment]
https://github.com/MihailDev/yii2-elfinder/blob/master/php/plugins/Sanitizer/plugin.php

**Comment by tuannda** [comment]
But I can't config it both in controllerMap or yii2-elfinder/php/controller...

**Comment by MihailDev** [comment]
```
'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
'connectOptions' => [/*here options*/]
           .............
'roots' => [
                [
                    'baseUrl'=>'@web',
                    'basePath'=>'@webroot',
                    'path' => 'files/global',
                    'name' => 'Global',
'options' => [/*here options*/]
                ],
................
        ]
        ]
    ],
```

**Comment by tuannda** [comment]
Thank you so much, I will try it again.

**Comment by tuannda** [comment]
My ControllerMap but not working..

`'elfinder' => [
			'class' => 'mihaildev\elfinder\Controller',
			'connectOptions' => [
				'uploadOverwrite' => false,
			],
			'access' => ['@'],
			'disabledCommands' => ['rm', 'duplicate', 'rename', 'extract', 'archive', 'help', 'netmount', 'info', 'cut',
				'download', 'mkfile'],
			'roots' => [
				[
					'baseUrl' => '',
					'basePath' => '@frontend/web',
					'path' => 'uploads',
					'name' => 'Uploads',
					'options' => [
						'plugins' => [
							'Sanitizer' => [
								'enable' => true,
								'targets' => array('\\', '/', ':', '*', '?', '"', '<', '>', '|', ' '),
								'replace' => '_'
							],
							'Normalizer' => [
								'enable' => true,
								'nfc' => true,
								'nfkc' => true,
								'lowercase' => true,
							],
						],
					],
				],
			],
		],`

**Comment by MihailDev** [comment]
I think you can help "Sluggable Plugin" https://github.com/MihailDev/yii2-elfinder/blob/master/php/plugins/Sluggable/plugin.php

currently only works settings for the component
my test settings 

```php
'elfinder' => [
			'class' => '\mihaildev\elfinder\PathController',
			


			'connectOptions' => [
				'bind' => array(
					'mkdir.pre mkfile.pre rename.pre archive.pre' => array(
						'Plugin.Sluggable.cmdPreprocess'
					),
					'upload.presave' => array(
						'Plugin.Sluggable.onUpLoadPreSave'
					)
				),
				'plugin' => [
					'Sluggable' => [
                        'enable' => true,
                        'lowercase' => false,
						'replacement' => '-'

                    ],
				],
			],
			'root' => [
				'baseUrl' => '@web/files/global',
				'basePath' => '@webroot/files/global',
				'access' => ['read' => '*', 'write' => '*'],
				'name' => 'Name', // Yii::t($category, $message)
				

			]
```

**Comment by tuannda** [comment]
Thank you so much!

I have another question related about uploadOverwrite
I can settings??
'connectOptions' => [
   'uploadOverwrite' => false
]

**Comment by tuannda** [comment]
```
'root' => [
				'options' => [
					'uploadOverwrite' => false,
				],
			],
```

**Comment by tuannda** [comment]
Thank you so much!

My example:

```
'controllerMap' => [
		'elfinder' => [
			'class' => 'mihaildev\elfinder\PathController',
			'access' => ['@'],
			'disabledCommands' => ['preview', 'rm', 'duplicate', 'rename', 'extract', 'archive', 'help', 'netmount', 'info', 'cut', 'download', 'mkfile'],
			'connectOptions' => [
				'bind' => array(
					'mkdir.pre mkfile.pre rename.pre archive.pre' => array(
						'Plugin.Sluggable.cmdPreprocess'
					),
					'upload.presave' => array(
						'Plugin.Sluggable.onUpLoadPreSave'
					)
				),
				'plugin' => [
					'Sluggable' => [
						'enable' => true,
						'lowercase' => false,
						'replacement' => '-'

					],
				],
			],
			'root' => [
				'baseUrl' => '',
				'basePath' => '@frontend/web',
				'path' => 'uploads',
				'name' => 'Uploads',
				'options' => [
					'uploadOverwrite' => false,
				],
			],
		],
	],
```

**Comment by fullflash** [comment]
Sluggable plugin removed i guess 
https://github.com/MihailDev/yii2-elfinder/blob/master/php/plugins/Sluggable/plugin.php

cant find in git of elfinder 
https://github.com/Studio-42/elFinder/tree/c715e05f46bbc1da9ab3188d1211c6ec6ccf9289/php/plugins
