### ISSUE TITLE
путь к frontend из backend в advanced

### ISSUE THREAD

**Issue by mozgobol** [MihailDev/yii2-elfinder#55]
ДОбрый день, установил, все работает. Но хотелось бы чтобы изображения складывались и показывались не из backend директории, а из frontend, шаблон advanced. Все перепробовал, ничего не помогает

**Comment by mozgobol** [comment]
Вопрос закрыт. разобрался. Большое спасибо за очень крутой виджет!

**Comment by Churakovmike** [comment]
@radiocity , спасибо за конфиг :) Все еще актуален )

**Comment by scorpsan** [comment]
настраивал в common\config\main.php

`'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'access' => ['manager'],
            'disabledCommands' => [
                'home', 'back', 'forward', 'up',
                //'reload',
                'netmount',
                //'mkdir',
                'mkfile',
                //'upload', 'open', 'download', 'getfile',
                'undo', 'redo', 'copy', 'cut', 'paste', 'rm', 'empty', 'duplicate', 'rename', 'edit', 'resize', 'chmod',
                //'selectall', 'selectnone', 'selectinvert', 'quicklook', 'info', 'extract', 'archive',
                'search', 'view', 'sort', 'preference', 'help', 'fullscreen'
            ], //отключение ненужных команд
            'plugin' => [
                [
                    'class'=>'\mihaildev\elfinder\plugin\Sluggable',
                    'lowercase' => true,
                    'replacement' => '-',
                ],
            ],
            'root' => [
                'baseUrl'=>'/files',
                'basePath'=>'@frontend/web/files',
                'path' => '',
                'name' => 'Uploads',
                'plugin' => [
                    'Sluggable' => [
                        'lowercase' => false,
                    ],
                ],
            ],
        ]
    ],`

по идее в таком случае из фронта не откроется а выдаст ошибку 404
из бэкенда откроется для всех кто имеет права выше manager
вставит адрес к файлу правильный
