### ISSUE TITLE
Абсолютные пути

### ISSUE THREAD

**Issue by Tahiaji** [MihailDev/yii2-elfinder#56]
Собственно, существуюет ли возможность использования абсолютных путей в ссылках?
Или единственный вариант указать имя хоста в baseUrl?

**Comment by MihailDev** [comment]
единственный вариант указать имя хоста в baseUrl

**Comment by MihailDev** [comment]
а чем он не устраивает?

**Comment by Tahiaji** [comment]
В принципе устраивает, единственное пытаюсь избегать в конфигах имя хоста указывать.

**Comment by MihailDev** [comment]
возьми сделай свой класс на основе LocalPath 
замени функцию
```php
public function getUrl(){
		return Yii::getAlias($this->baseUrl.'/'.trim($this->path,'/'));
	}
```

на 
```php
public function getUrl(){
		return Yii::app()->request->hostInfo.Yii::getAlias($this->baseUrl.'/'.trim($this->path,'/'));
	}
```
