### ISSUE TITLE
Кодировка загружаемых имен файлов

### ISSUE THREAD

**Issue by Vetal79** [MihailDev/yii2-elfinder#58]
Доброго времени суток! Использую Windows 10 + OpenServer elfinder при загрузке показывает нормальные имена файлов, но в Windows Explorer они отображаются как "кракозябры" из-за этого не работаю ссылки на них. Подскажите пожалуйста в каком направлении копать, чтоб имена файлов корректно отображались.

**Comment by MihailDev** [comment]
как одно из решений это использования транслита!

```php
'elfinder' => [
			'class' => '\mihaildev\elfinder\PathController',
			


			'connectOptions' => [
				'bind' => array(
					'mkdir.pre mkfile.pre rename.pre archive.pre' => array(
						'Plugin.Sluggable.cmdPreprocess'
					),
					'upload.presave' => array(
						'Plugin.Sluggable.onUpLoadPreSave'
					)
				),
				'plugin' => [
					'Sluggable' => [
                        'enable' => true,
                        'lowercase' => false,
						'replacement' => '-'

                    ],
				],
			],
			'root' => [
				'baseUrl' => '@web/files/global',
				'basePath' => '@webroot/files/global',
				'access' => ['read' => '*', 'write' => '*'],
				'name' => 'Name', // Yii::t($category, $message)
				

			]
```

**Comment by Vetal79** [comment]
Спасибо большое! Не подскажите где, посмотреть в исходном коде elfinder функцию сохранения имени файла для использования функции кодировки iconv с utf8 в windows 1251. Спасибо.

**Comment by MihailDev** [comment]
это вам не в elfinder  искать нужно а правильно настроить сервер

1) все ли файлы проекта в утф8 (без бум) кодировке
2) страница на которой вы грузите все в какой кодировке отображается? должно тоже быть в утф8
3) сам сервер работает в какой кодировке по умолчанию? должно тоже быть в утф8 http://htaccess.net.ru/doc/AddType-charset/CharsetDefault.php

советую работать с утф8 везде меньше проблем с кодировками!
почитайте статьи
по настройке
https://school-php.com/tricks/18/vyistavlyaem-kodirovku-utf-8 
о кодировках
https://habrahabr.ru/post/113715/
https://habrahabr.ru/post/158639/

во всех статьях много пишут о хранении данных в битах я так думаю это вам ничего не даст
но если интересно почитайте но везде пишут о том что надо работать с утф8 и при необходимости конвертировать в необходимую кодировку (крайне редко бывает)

**Comment by MihailDev** [comment]
но если вам очень нужна функция которая работает с кодированием то вот оно
https://github.com/MihailDev/yii2-elfinder/blob/master/php/elFinderVolumeDriver.class.php#L2416

**Comment by MihailDev** [comment]
также для смены кодирования у ел в настройках есть 
https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#encoding
и
https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options-2.1#locallocale
```php
'root' => [
            'baseUrl'=>'@web',
            'basePath'=>'@webroot',
            'path' => '/Upload/Tasks',
            'name' => 'Tasks'
            'options' => ['encoding' => 'my encoding', 'locale' => 'my locale']
        ],
````

**Comment by Vetal79** [comment]
Большое Вам Спасибо за консультации!!! Осталось решить последнюю задачу, теперь вставка ссылки в ckeditor (файл на сервер загружен на сервер и отображается нормально помогло 'options' => ['encoding' => 'WINDOWS-1251'] как "Задание.docx") но в ссылке отображается как %C7%E0%E4%E0%ED%E8%E5.docx ,соответственной веб-сервер его не видит и не дает его скачать.

**Comment by MihailDev** [comment]
проблема опять в тех же граблях не соответствие кодировок! везде на сервере должна быть одна кодировка! я не могу сказать в чём у вас проблема! возможно в дб куда вы сохраняете вашу запись возможно на самой странице редактирования записи! я дал вам ряд статей там описано как надо настраивать всё под утф8 если она не устраивает настройте всё под 1251 но не работайте с не соответствующими кодировками!

что сейчас происходит 
1) открытие elfinder страница в утф8 (так настроено по умолчанию для смены надо изменить фаил vendor\mihaildev\yii2-elfinder\views\manager.php)
2) сохранение файла имя приходит в конект (vendor\mihaildev\yii2-elfinder\views\connect.php) в кодировке утф8 и сохранялось в 1251 что вело к иероглифам после установки 'encoding' => 'WINDOWS-1251' приходит в кодировке утф8, перекодируется в 1251 и сохранялось в 1251
3) скрипт из manager (утф8) передаёт на страницу записи (1251) имя файла
4) запись в 1251 сохраняется в дб неизвестной кодировки

п.с. вы постоянно будете иметь траблы с кодировкой пока всё не переведёте на утф8! вы сейчас работаете на лок. машине но вам надо будет перенести куда то  ваш проект а там настроено всё под утф8 и у вас снова траблы! 

удачи!

**Comment by gaginsgagins** [comment]
Конфиг:
```
'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'connectOptions' => [
                'bind' => array(
                    'mkdir.pre mkfile.pre rename.pre archive.pre' => array(
                        'Plugin.Sluggable.cmdPreprocess'
                    ),
                    'upload.presave' => array(
                        'Plugin.Sluggable.onUpLoadPreSave'
                    )
                ),
                'plugin' => [
                    'Sluggable' => [
                        'enable' => true,
                        'lowercase' => false,
                        'replacement' => '-'

                    ],
                ],
            ],
            'access' => ['@', '?'],
            'root' => [
                'path' => 'upload/upimages',
                'name' => 'Global'
            ],
           
        ]
    ],
```
Транслитерация не происходит. Подскажите, что не так?

**Comment by MihailDev** [comment]
https://github.com/MihailDev/yii2-elfinder#%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%9F%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%BE%D0%B2

**Comment by gaginsgagins** [comment]
Хорошо взял конфиг из этого примера.
`           'plugin' => [
                [
                    'class'=>'\mihaildev\elfinder\plugin\Sluggable',
                    'lowercase' => true,
                    'replacement' => '-'
                ],
            ],

            'access' => ['@', '?'],
            'root' => [
                'path' => 'upload/upimages',
                'name' => 'Global',
                'plugin' => [
                    'Sluggable' => [
                        'lowercase' => false,
                    ]
                ],

            ],`
Теперь очевидно плагин подключился, но теперь файлы с русскими буквами не транслитеруются, а просто удаляются все русские буквы из его имени. в итоге получаю ошибку:
![s3](https://cloud.githubusercontent.com/assets/25243076/24790688/f6161424-1b7f-11e7-8d9e-d8d9f16c1ac9.PNG)
если в имени файла есть другие символы, цифры или англ буквы то остаются только они и загрузка проходит успешно.

**Comment by gaginsgagins** [comment]
Сам же и отвечу. Нужно включить расширение для php **intl** поскольку плагин Sluggable использует стандартный хелпер **Inflector**, который в свою очередь и использует  **intl**
