### ISSUE TITLE
Amazon S3 connection failing

### ISSUE THREAD

**Issue by DarthLegiON** [MihailDev/yii2-elfinder#59]
After full configuration of Amazon keys XHR in File Browser returns this:

{"error":["errConf","errNoVolumes"],"debug":["Driver \"elFinderVolumeS3\" : curl_setopt_array(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead"]}

How it can be fixed? Thanks!

**Comment by MihailDev** [comment]
You can try set CURLOPT_SSL_VERIFYHOST = 2

```php
'root' => [
...
				'access' => ['read' => '*', 'write' => '*'],
				'name' => 'Name',
				'options' => [
					's3' => [
						'curl.options' => [CURLOPT_SSL_VERIFYHOST => 2]
					]
				]

			]
```

**Comment by MihailDev** [comment]
and you need before set options update files 
https://github.com/MihailDev/yii2-elfinder/commit/ba295fe80de6208e4013b3f9bd36a83645eca17b

**Comment by DarthLegiON** [comment]
@MihailDev sorry, but it didn't help.
Here is my config.

`
'root' => [
                'class' => \mihaildev\elfinder\S3Path::className(),
                'access' => ['read' => '*', 'write' => '*'],
                'name' => 'S3',
                'bucket' => 'hr-php',
                'path' => 'test', // todo поменять
                'region' => 'us-east-1',
                'accessKey' => 'access_key', // вставить публичный ключ доступа юзера
                'secretKey' => 'secret_key', // вставить секретный ключ доступа юзера
                'options' => [
                    's3' => [
                        'curl.options' => [CURLOPT_SSL_VERIFYHOST => 2]
                    ]
                ]
            ],
`

**Comment by MihailDev** [comment]
try 
```php
'options' => [
			's3' => [
				'ssl.certificate_authority' => null,
				'curl.options' => [CURLOPT_SSL_VERIFYHOST => 2, CURLOPT_SSL_VERIFYPEER => false]
			]
		]
```
