### ISSUE TITLE
Некорректная настройка сервера. Отсутствуют корневые директории достуные для чтения.

### ISSUE THREAD

**Issue by hrupin** [MihailDev/yii2-elfinder#61]
Установил через composer, elfinder запускается, в консоли ошибок нет. Но выдает 

> Некорректная настройка сервера.
> Отсутствуют корневые директории достуные для чтения.

Права поставил 777

**Comment by MihailDev** [comment]
покажи конфиг фаил попробуем разобраться

**Comment by hrupin** [comment]
`'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\Controller',
            'access' => ['@'], 
            'disabledCommands' => ['netmount'],
            'roots' => [
                [
                    'baseUrl' => '@storageUrl',
                    'basePath' => '@storage',
                    'path'   => '/uploads',
                    'access' => ['read' => '@', 'write' => '@']
                ]
            ]
        ]
    ],`

**Comment by MihailDev** [comment]
у вас ошибка в конфиге
```php
'access' => ['read' => '@', 'write' => '@']
```
тут возможно указать либо * то есть для всех у кого есть  глобальный доступ ('access' => ['@'])
либо указать конкретное разрешение (Rbac permission) 'access' => ['read' => '*', 'write' => 'canWrite']

на данный момент у вас ошибка из-за того что вы указали несуществующее разрешение

**Comment by hrupin** [comment]
Спасибо, теперь понял что я делал не так

**Comment by DmitryFX** [comment]
А где найти этот конфиг файл? Поставил плагин для редактора fred в modx, локально все работало, на сервере - та же ошибка.
