### ISSUE TITLE
кавычки менятяються на &quot;

### ISSUE THREAD

**Issue by orpat** [MihailDev/yii2-elfinder#65]
Доброго времени суток!
Помогите пожалуйста, есть самописный сайт. Туда интегрировал elfinder 2.0. Но есть один нюанс, после сохранения файлов все кавычки в файле меняются на &quot; как это побороть не знаю. Заранее спасибо!

**Comment by MihailDev** [comment]
https://github.com/Studio-42/elFinder/blob/master/php/plugins/Sanitizer/plugin.php

**Comment by MihailDev** [comment]
```
'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
'connectOptions' => [/*here options*/]
           .............
'roots' => [
                [
                    'baseUrl'=>'@web',
                    'basePath'=>'@webroot',
                    'path' => 'files/global',
                    'name' => 'Global',
'options' => [/*here options*/]
                ],
................
        ]
        ]
    ],
```

**Comment by orpat** [comment]
Не совсем понял куда это нужно прописать?

**Comment by orpat** [comment]
У меня elfinder запускаеться вот таким вот образом:
<script type="text/javascript" charset="utf-8"> 
$(function () { 
var myCommands = elFinder.prototype._options.commands; 
var disabled = ['resize', 'help', 'select']; 
// Not yet implemented commands in ElFinder.Net 
$.each(disabled, function (i, cmd) {
	(idx = $.inArray(cmd, myCommands)) !== -1 && myCommands.splice(idx, 1); 
});
 
var selectedFile = null; 
var options = { 
url: '/servers/control/getftp/<?php echo $server['server_id']  ?>', // connector route defined in the project folder App_Start\RouteConfig.cs 
rememberLastDir: false, // Prevent elFinder saving in the Browser LocalStorage the last visited directory 
commands: myCommands,
//commandsOptions: 
lang: 'ru', // elFinder supports UI and messages localization. Check the folder Content\elfinder\js\i18n for all available languages. Be sure to include the corresponding .js file(s) in the JavaScript bundle. 
uiOptions: { // UI buttons available to the user 
toolbar: [ ['back', 'forward'], ['reload'], ['home', 'up'], ['mkdir', 'mkfile', 'upload'], ['open', 'download'], ['info'], ['quicklook'], ['copy', 'cut', 'paste'], ['rm'], ['duplicate', 'rename', 'edit','extract', 'archive'], ['view', 'sort'] ] }, 
handlers: { select: function (event, elfinderInstance) { 
if (event.data.selected.length == 1) { var item = $('#' + event.data.selected[0]); if (!item.hasClass('directory')) { selectedFile = event.data.selected[0]; $('#elfinder-selectFile').show(); return; } } 
$('#elfinder-selectFile').hide(); selectedFile = null; } } 
}; 
$('#elfinder').elfinder(options).elfinder('instance'); $('.elfinder-toolbar:first').append('<div class="ui-widget-content ui-corner-all elfinder-buttonset" id="elfinder-selectFile" style="display:none; float:right;">'+ '<div class="ui-state-default elfinder-button" title="Select" style="width: 100px;"></div>'); $('#elfinder-selectFile').click(function () { 
if (selectedFile != null) $.post('file/selectFile', { target: selectedFile }, function (response) { alert(response); }); }); }); </script>

Как тут передать плагин sanitizer&?

**Comment by orpat** [comment]
Вроде как разобрался, но сейчас вышла другая проблема. Данные для авторизации я передаю вот так:
customData : {
					host: '<?php echo $server['location_ip'] ?>',
					user: 'gs<?php echo $server['server_id']  ?>',
					pass: '<?php echo $server['server_password'] ?>',
					}
В самом коннекторе я прописал следующие:
'roots' => array(
		array(
			'driver' => 'FTP',
			'host'   => $_GET['host'],
			'user'   => $_GET['user'],
			'pass'   => $_GET['pass'],
			'port'   => '21',
			'mode'   => 'passive',
			'path'          => '/',
Само подключение происходит, я могу копировать, удалять переименовывать названия  всех файлов и директории. Но не могу загружать новые файлы, а так же редактировать. Выходит ошибка: "Invalid backend configuration. Readable volumes not available.". Если же не передовать данные через html страницу, а на прямую прописать данные подключения в коннекторе, то такой проблемы нет. В чем может быть проблема?

**Comment by MihailDev** [comment]
а зачем так извращаться! 
насколько я понял вы пытаетесь сделать свой контроллер на базе моего!?
просто неправильно предавать открыто параметры подключения!
объясните задачу а то я не пойму что вам нужно!!!

**Comment by orpat** [comment]
Все заработало, просто на место get использовал request. Спасибо за помощь.

**Comment by Kravalg** [comment]
@orpat пилим, пилим костыли...
