### ISSUE TITLE
Транслитерация

### ISSUE THREAD

**Issue by zslavik** [MihailDev/yii2-elfinder#66]
Как возможно использовать транслитерацию имен изображений при загрузке?

**Comment by ivansal** [comment]
можно использовать `TransliteratorHelper` он хорошо работает

**Comment by MihailDev** [comment]
я его не добавил в новую версию но походу надо вернуть! сорри! не успеваю!

**Comment by zslavik** [comment]
А в какой версии он есть и как им воспользоваться? Спасибо.

**Comment by MihailDev** [comment]
самое интересное что ни в одну версию он так и не попал но я скоро это исправлю!
вот код если нужен https://github.com/MihailDev/yii2-elfinder/commit/40ba94bdfe31a21b9a064a3973ab2b7b80df0111
