### ISSUE TITLE
Как включить debug режим

### ISSUE THREAD

**Issue by Kravalg** [MihailDev/yii2-elfinder#67]
Мне требуется включить debug mode, но в документации я этого не нашел.

https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options#debug

**Comment by ivansal** [comment]
https://github.com/MihailDev/yii2-elfinder/blob/master/BaseController.php#L33 вот эту штуку настроить

**Comment by MihailDev** [comment]
как то так
```
'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\Controller',
            'connectOptions' => ['debug' => true]
...
```

**Comment by Kravalg** [comment]
Спасибо, решено.
Было бы здорово увидеть эти в документации для последующих разработчиков

**Comment by MihailDev** [comment]
может сделаю какой нить фак! но не сейчас! много работы!
