### ISSUE TITLE
Неизвестная ошибка

### ISSUE THREAD

**Issue by Hibiki08** [MihailDev/yii2-elfinder#70]
Здравствуйте. При загрузке изображения появляется эта ошибка: http://joxi.ru/D2P3MvLTXK6pm3
Вот мой конфиг: http://joxi.ru/DrlbJj0UQPxd2P
В каком направлении нужно смотреть?

**Comment by MihailDev** [comment]
для начала узнать какую команду не может выполнить!
что делалось перед тем как вышла данная ошибка?

для отслеживания нужно посмотреть запросы у вас на скрине как раз открыт раздел нетворк
в нём все запросы скинте все запросы которые выполнялись так узнаем какая команда выполнялась!

**Comment by Hibiki08** [comment]
> что делалось перед тем как вышла данная ошибка?
собственно, она была с самого начала, как я пытаюсь поставить расширение на CKEditor.
Вот все запросы: http://joxi.ru/Y2LKNv5FG0P1m6

**Comment by MihailDev** [comment]
покажите код подключение СК с Елф
и пожалуйста сделайте скрин с развёрнутыми полем  Name дабы можно было видеть все параметры запросов

**Comment by Hibiki08** [comment]
Код подключения: http://joxi.ru/l2ZlWpkUZK8XrJ
Поле "name": http://joxi.ru/ZrJd7vMTZq1X2j

**Comment by Hibiki08** [comment]
Михаил?

**Comment by MihailDev** [comment]
сорри уезжал!

**Comment by MihailDev** [comment]
вижу что у вас ссылки почему то не верные формируются
1 запрос просто ?path.....
2 запрос верный 
3 опять неверный и почему то при этом пустой без csrf
4 частично верный но опять без  csrf

где то в путях ошибка по идее при старте должен быть  один запрос или 2 если ранее была выделена папка
