### ISSUE TITLE
Не выходит использовать расширение yii2-elfinder на версии yii-basic-app-2.0.8

### ISSUE THREAD

**Issue by domeniktoredo** [MihailDev/yii2-elfinder#73]
Не выходит использовать расширение yii2-elfinder на версии yii-basic-app-2.0.8.

Не выходит установить yii2-elfinder через composer.
Использую xampp.
Перед этим устанавливал yii2-ckeditor через composer все было хорошо.
А при установке yii2-elfinder выдает ошибку установки.

`C:\xampp\htdocs\first-e-shop.local\www>composer require --prefer-dist mihaildev/yii2-elfinder "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - mihaildev/yii2-elfinder 1.0.0 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.0.1 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.0.2 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.0.3 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.0.4 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.0.5 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.1.0 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.1.1 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.1.2 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.1.3 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.2.0 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - mihaildev/yii2-elfinder 1.2.1 requires yiisoft/yii2-jui * -> satisfiable by yiisoft/yii2-jui[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6].
    - yiisoft/yii2-jui 2.0.6 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.5 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.4 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.3 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.2 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.1 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - yiisoft/yii2-jui 2.0.0 requires bower-asset/jquery-ui 1.11.*@stable -> no matching package found.
    - Installation request for mihaildev/yii2-elfinder * -> satisfiable by mihaildev/yii2-elfinder[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.2.0, 1.2.1].
Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Installation failed, reverting ./composer.json to its original content.
C:\xampp\htdocs\first-e-shop.local\www>`

Получилось установить yii2-elfinder через composer.
Для этого пришлось изменить настройки в файле first-e-shop.local\www\composer.json.
Конкретнее изменил

`"minimum-stability": "stable",`

на 

`"minimum-stability": "dev",`

и добавил

`"prefer-stable": true,`

Вместе получилось

`"minimum-stability": "dev",
"prefer-stable": true,`

Написало что все установилось и все хорошо.
При дальнейшем разборе урока оказывается что у Вас в уроке все работает нормально а у меня выдает ошибку при попытке открыть загрузчик elfinder 2.0
(адрес в браузере `http://first-e-shop.local/elfinder/manager?filter=image&CKEditor=product-content&CKEditorFuncNum=1&langCode=ru`)

``ReflectionException`
`Class` yii\jui\JuiAsset does not exist`

![error_yii2_lesson_29](https://cloud.githubusercontent.com/assets/13270239/19040757/1b7eef12-898e-11e6-8b57-08f80e1b6672.jpg)

Я подозреваю что это последствия первой ошибки, которую я решил. Возможно решение было не верным?
Я использую версию yii-basic-app-2.0.8

Помогите разобраться!

**Comment by MihailDev** [comment]
вас скорее всего не установлен composer global require "fxp/composer-asset-plugin:^1.2.0"
http://www.yiiframework.com/doc-2.0/guide-start-installation.html

если это не поможет или у вас всё стоит то с данной проблемой надо писать сюда https://github.com/yiisoft/yii2-jui
это в их пакете проблема!

**Comment by oscarhandsome** [comment]
`composer global require "fxp/composer-asset-plugin:dev-master"`
it helped to me
