### ISSUE TITLE
Don't work Preview for PDF files

### ISSUE THREAD

**Issue by Kravalg** [MihailDev/yii2-elfinder#76]
Preview on [official site](http://studio-42.github.io/elFinder/) for PDF files is fine and good working. 
But in my project not working.

Main config:
```
'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'connectOptions' => ['debug' => true],
            'access' => ['@'],
            'root' => [
                'class' => 'mihaildev\elfinder\flysystem\Volume',
                'path' => $dropbox['path'],
                'component' => [
                    'class' => 'creocoder\flysystem\DropboxFilesystem',
                    'token' => $dropbox['token'],
                    'app' => $dropbox['app'],
                ]
            ],
        ]
```
I am testing now.
When press the Preview button, no ajax requests there.

**Comment by Kravalg** [comment]
What you can say about it?

**Comment by MihailDev** [comment]
у меня превью тоже не работает! но на основном сайте у меня также не работает!

**Comment by Kravalg** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/9444106/20248925/349e7aa4-a9ef-11e6-963d-ece9ae209dcb.png)
