### ISSUE TITLE
Iframe height

### ISSUE THREAD

**Issue by ipppinto** [MihailDev/yii2-elfinder#78]
Hi,

In my yii2 the iframe height is like this:

![snap 2016-11-05 at 14 55 57](https://cloud.githubusercontent.com/assets/6302542/20030969/f48344d2-a367-11e6-8f13-85a69ec1f627.jpg)

It is possible resize to 100% of my div?

**Comment by MihailDev** [comment]
```php
echo ElFinder::widget([

    'controller'       => 'elfinder',
'containerOptions'       => ['style'=>'height: 400px;'],
//'frameOptions'       => ['style'=>'width: 100%; height: 100%; border: 0;'], //by default

]);
```
