### ISSUE TITLE
Unable to connect to backend. HTTP error 500

### ISSUE THREAD

**Issue by HenryDewa** [MihailDev/yii2-elfinder#79]
Hai I'm getting error while running on basic apps yii2

![elfinder](https://cloud.githubusercontent.com/assets/2367303/21001027/a46f4dc6-bd50-11e6-8ce7-ffa72a5d6d83.PNG)

This is my config :
'controllerMap' => [
        'elfinder' => [
            'class' => 'mihaildev\elfinder\PathController',
            'access' => ['@'],
            'root' => [
                [
                    'baseUrl'=>'@web',
                    'basePath'=>'@webroot',
                    'path' => 'files/global',
                    'name' => 'Global'
                ],
            ],
           
        ]
    ],

Thanks

**Comment by MihailDev** [comment]
show me log files
