### ISSUE TITLE
Disable real file path from being shown (prevent direct access)

### ISSUE THREAD

**Issue by jhon100** [MihailDev/yii2-elfinder#81]
Hello, I would like to thank for the extension, I am using it and it works very well. 
Could you tell me how I could configure or edit your extension to prevent any user from having direct access to the files ?
I've been looking at the elfinder documentation and found this post:

https://github.com/Studio-42/elFinder/wiki/Disable-real-file-path-from-being-shown

I looked at the code of your extension but I did not understand where I could implement what the post suggests. If I can disable real path, so I can put a .htaccess file in my root folder.

**Comment by MihailDev** [comment]
```php
                [
                   'options' => ['URL' => ''], // or ['URL' => null]
                    'basePath'=>'@webroot',
                    'path' => 'files/global',
                    'name' => 'Global'
                ],
```

**Comment by jhon100** [comment]
Thanks it worked :)
