### ISSUE TITLE
Регистрация Js

### ISSUE THREAD

**Issue by Pavlyukovsky** [MihailDev/yii2-elfinder#87]
Возникла проблема с регистрацией Js, http://prntscr.com/e8nwvr. Пробовал использовать noConflict, не помогло. 

Нашел решение: нужно обернуть скрипты в подгружаемом файле(Например в manager.php) после загрузки всего $this->renderJs('JS',\yii\web\View::POS_LOAD).

Разработчики не могли бы до пилить такой функционал? Или подсказать как решить эту проблему.

**Comment by MihailDev** [comment]
я не до конца понимаю что именно не работает у вас? вы пытаетесь добавить свой джс?

**Comment by Pavlyukovsky** [comment]
Я уже разобрался. Ломал один скрипт, когда я делаю минимизацию скриптов. Я
его теперь подключаю отдельно.

Было бы не плохо вам обернуть ваши скрипты и подключать их после загрузки
странницы.

P.S. Спасибо что ответили:)

2017-02-16 11:29 GMT+02:00 Mihail <notifications@github.com>:
